language: ruby
sudo: false
cache: bundler
before_script: bundle install --jobs=3 --retry=3

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

gemfile:
  - gemfiles/Gemfile.rails-4-2stable
  - gemfiles/Gemfile.rails-5-0stable
  - gemfiles/Gemfile.rails-5-1stable
